# Generated by Django 4.0.5 on 2022-08-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
