# Generated by Django 4.0.5 on 2022-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusers',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
