# Generated by Django 4.0.5 on 2022-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionscore',
            name='answer',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
