# Generated by Django 4.0.5 on 2022-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.SlugField(max_length=14, unique=True),
        ),
    ]
