# Generated by Django 4.0.5 on 2022-08-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_time_alter_answer_question'),
        ('groups', '0001_initial'),
        ('accounts', '0004_alter_user_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_score', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_score', to='questions.test'),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquestiontime',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_time', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='userquestiontime',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_time', to='questions.test'),
        ),
        migrations.AlterField(
            model_name='userquestiontime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_time', to=settings.AUTH_USER_MODEL),
        ),
    ]
