# Generated by Django 4.0.5 on 2022-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='overall_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
